# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Aug 16 09:33:48 2011

import wx
from wx.lib.scrolledpanel import ScrolledPanel
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class CmdGenAuto(wx.Panel):
    def __init__(self, *args, **kwds):
        wx.Panel.__init__(self, *args, **kwds)
        
        bSizer5 = wx.BoxSizer( wx.VERTICAL );
    
        fgSizer3 = wx.BoxSizer(wx.HORIZONTAL)        
    
        m_staticText6 = wx.StaticText( self, wx.ID_ANY, "Class")
        m_staticText6.Wrap( -1 );
        fgSizer3.Add( m_staticText6, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 5 );
        
        cmdClass = wx.Choice( self, wx.ID_ANY);
        cmdClass.SetSelection( 0 );
        fgSizer3.Add( cmdClass, 1, wx.ALL|wx.ALIGN_RIGHT|wx.EXPAND, 5 );
        
        m_staticText7 = wx.StaticText( self, wx.ID_ANY, "Cmd");
        m_staticText7.Wrap( -1 );
        fgSizer3.Add( m_staticText7, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 5 );
        

        cmd = wx.Choice( self, wx.ID_ANY);
        cmd.SetSelection( 0 );
        fgSizer3.Add( cmd, 1, wx.ALL|wx.ALIGN_RIGHT|wx.EXPAND, 5 );
        
        bSizer5.Add( fgSizer3, 0, wx.EXPAND, 5 );
        
        

        properties = ScrolledPanel(self, -1, style = wx.TAB_TRAVERSAL|wx.SUNKEN_BORDER, name="panel1")
        properties.SetAutoLayout(1)
        properties.SetupScrolling()
        
        self.prop_sizer = wx.FlexGridSizer(cols=4)
        properties.SetSizer(self.prop_sizer)
        
        bSizer5.Add( properties, 1, wx.EXPAND | wx.ALL, 5 );

        #properties = wx.Panel( self, wx.ID_ANY);
        #bSizer5.Add( properties, 1, wx.ALL|wx.EXPAND, 5 );
        
        
        bSizer6 = wx.BoxSizer( wx.HORIZONTAL );
        #snd2host = wx.CheckBox( self, wx.ID_ANY, "Send to host");
        #snd2host.SetValue(False); 
        #bSizer6.Add( snd2host, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL|wx.EXPAND, 5 );
        
        #m_staticText5 =  wx.StaticText( self, wx.ID_ANY, "Endpoint");
        #m_staticText5.Wrap( -1 );
        #bSizer6.Add( m_staticText5, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 );

        m_cmdText =  wx.StaticText( self, wx.ID_ANY, "cmd:                                                                        ");
        bSizer6.Add( m_cmdText, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 );
        
        #endpoint =  wx.SpinCtrl( self, wx.ID_ANY);
        #bSizer6.Add( endpoint, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 );
        
        
        bSizer6.Add( (0, 0) , 1, wx.EXPAND, 5 );
        
        send = wx.Button( self, wx.ID_ANY, "Send");
        bSizer6.Add( send, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 );		
        #bSizer6.Add( send, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 );
        
        bSizer5.Add( bSizer6, 0, wx.EXPAND, 5 );
        
        self.SetSizer( bSizer5 );
        self.Layout();
        
        #export
        self.cmdClass = cmdClass
        self.cmd = cmd
        self.properties = properties
        self.m_cmdText = m_cmdText       
        #self.endpoint = endpoint
        #self.snd2host = snd2host
# end of class CmdGenAuto


